import random

estudiantes = [
  'AMEZQUITA NUÑEZ JUAN DAVID',
  'CORREA RIVERA ANGEL MANUEL',
  'DIAZ SILVERA ANDRES FELIPE',
  'HERNANDEZ MOLINA SANTIAGO ',
  'MORALES PEREZ ANDRES NICOLAS',
  'MORENO SANCHEZ SANTIAGO ANDRES',
  'NEIRA MARTINEZ JUAN DAVID	',
  'PEREZ HERNANDEZ SEBASTIAN ',
  'PEREZ MOLINA JAIDER NICOLAS',
  'PIRACOCA ARCOS JHON ALEXIS',
  'QUIROZ PARRA BRAYAN NICOLAS',
  'RODRIGUEZ PESCA ANDRES FELIPE',
  'SIERRA VARGAS SAYIRA CAMILA',
  'SOLANO SILVA JOSE GABRIEL',
  'SOLER GALINDO HARRIZON ALEXANDER',
];



#print(random.randrange(1,15))
print(random.choices(estudiantes))